TEAM = [('Dhiraj Tendulkar','24302A0004'),('Vidhi Mahato','24302A0028'),('Gaurav Mhatre','24302A0067'),('Varun Patil','24302D0074')]
TITLE = 'Skill Bridge'
SUBTITLE = 'Community Employment and Skill Matching Portal'

# Each entry supplies independently phrased narrative for the four reports.
TEXT = {
'1.1': [
'Skill Bridge grew out of our Community Engagement Project at Khalsa College, Matunga. Our four-member team completed all three field visits at the same college. We gathered student inputs manually by circulating a Google Form. The project connects this requirement-gathering work with a web portal for placement opportunities, practical training, applications and guidance. In this report, I explain the shared project through its community purpose and the technical decisions used to implement it.',
'Our CEP work brought the team to Khalsa College in Matunga on three occasions. Students were the primary community for the project, and we distributed a Google Form to collect their responses manually. Skill Bridge was developed around placement support: finding suitable opportunities, understanding skill requirements and following up on applications. This report presents the work from my perspective while retaining the common facts and outcomes of the team project.',
'The setting for our project was Khalsa College, Matunga, where the team carried out all three visits. We used a Google Form circulated among students to gather information for the project. The resulting application, Skill Bridge, brings placement-related tasks into a shared system with different access for students and coordinators. I describe both the fieldwork context and the implementation so that the relationship between the community problem and the software remains clear.',
'Skill Bridge is the web application developed for our Community Engagement Project. All three visits took place at Khalsa College, Matunga, and the team collected genuine student responses by distributing a Google Form manually. The portal addresses employment preparation and placement coordination through connected student and staff workspaces. My report explains how the project was organised, how its features operate and what the available technical evidence establishes.'
],
'1.2': [
'The problem addressed is the difficulty of connecting a student’s interests and skills with suitable placement opportunities while maintaining a clear record of applications and support needs. A listing alone does not explain whether a role fits a profile or what preparation is required. Coordinators also need a consistent way to review applications, manage workshops and respond to requests. Skill Bridge treats these activities as related parts of one process.',
'A placement-support system must do more than display vacancies. Students need to understand relevance, eligibility and the next action, while coordinators need visibility into applications and training participation. The project therefore addresses the lack of a connected workflow between opportunity discovery, skill preparation and follow-up. The statement describes the problem our solution targets; a quantitative baseline for the college is [To be added].',
'The central design problem is keeping opportunity information, student preferences and coordinator decisions connected. When these records are handled separately, a student can struggle to identify a suitable opening or understand an application’s progress. The proposed portal gives each participant an appropriate workspace and records the interaction between them. Verified numerical findings from the collected Google Form responses are [To be added].',
'Our project focuses on the practical gap between seeing an opportunity and receiving useful placement support. Students need relevant listings and visible progress; coordinators need structured records for decisions, training and guidance. The application was designed to support that whole sequence. Claims about the frequency or scale of these difficulties require the field-response analysis, which is [To be added].'
],
'1.3': [
'The need for the project is a clearer connection between information and action. Students should be able to save an opening, submit an application and later see its status. Training and guidance should also have a recorded follow-up rather than ending at a request. Separate permissions make the portal easier to demonstrate and help protect student-specific records during routine use.',
'A common portal can reduce the effort required to move between opportunity information, applications and support requests. It also makes responsibilities visible: students manage their own records, coordinators handle operational decisions, and administrators maintain the system. This separation is important for both usability and data protection. Any measured reduction in administrative effort remains to be established through a live evaluation.',
'Skill Bridge is needed as a practical link between placement information and the actions taken on it. Searchable listings are useful only when students can act on them and coordinators can respond. Bringing applications, workshops and guidance into the same database provides continuity. The project also provides a setting in which role separation and accountable record keeping can be demonstrated.',
'The value of the project lies in making placement support understandable and traceable. A student should know what is available, what has been submitted and what response has been received. Staff should have an organised queue of work rather than relying on the student interface. The portal supports these needs without presenting a matching score as a guarantee of selection.'
],
'1.4': [
'The objectives link the community purpose to functions that can be checked in the application. I have separated the direct placement-support goals from the supporting requirements for usability and maintenance.',
'We translated the project purpose into observable system functions. The primary objectives describe what users should accomplish; the secondary objectives concern the quality and continuity of those functions.',
'The following objectives provide a practical basis for evaluating the work. They focus on completed user actions and protected records rather than unmeasured promises about employment outcomes.',
'Our objectives were framed around the tasks the portal should support. The distinction below keeps the student-facing purpose clear while recognising the need for reliable administration and validation.'
],
'1.5': [
'The implemented scope covers a local web application with student, placement coordinator and administrator access. It includes profiles, opportunity discovery, explained matching, applications, workshops, feedback, guidance, research summaries and administrative backup tools. The scope does not establish employer hiring decisions, actual placement gains or live institutional adoption. Hosting details and a signed handover record are [To be added].',
'This report covers the developed portal and the associated three-visit CEP work. The system manages placement-support records and presents research information through role-appropriate views. It does not promise employment, automate employer selection or establish a measured improvement in placement rates. Production-mode operation has been tested locally; a live hosting address and evidence of organisational handover are [To be added].',
'The project boundary is the student–coordinator workflow and the administration needed to maintain it. The application supports opportunity records, applications, training participation and support requests, with research reporting alongside these operations. Recruitment decisions outside the portal and long-term employment outcomes are beyond the demonstrated scope. External deployment and institutional acceptance records are [To be added].',
'Skill Bridge covers the technical portal, its database, the documented workflows and the fieldwork setting. It supports placement preparation and coordination rather than replacing an employer’s assessment process. Matching remains advisory, and no verified claim is made about placement-rate improvement. The final hosting location, approved operational owner and formal handover details are [To be added].'
],
'1.6': [
'The project aligns with SDG 4, Quality Education, through access to skill-development opportunities and clearer guidance. It also relates to SDG 8, Decent Work and Economic Growth, by helping students explore employment opportunities and prepare for relevant roles. These links describe the purpose of the intervention. They do not establish a measured change in educational or employment indicators.',
'Skill Bridge connects most directly with SDG 4 and SDG 8. Training discovery and guidance support learning beyond the classroom, while opportunity information and application tracking support preparation for work. The contribution is at the level of access and coordination. A numerical assessment of SDG outcomes would require follow-up evidence after actual use.',
'The educational aspect of the portal supports SDG 4 by organising training and career guidance. Its employment-support functions are consistent with SDG 8 because they make opportunities and preparation requirements easier to explore. The report treats this as alignment of project objectives, not proof that the software has already improved employment conditions.',
'Two goals provide a suitable framework for the project: SDG 4, Quality Education, and SDG 8, Decent Work and Economic Growth. Workshops, guidance and explained matching connect learning needs with career preparation. The application can support progress toward these goals, but a verified community-impact measurement remains a separate evaluation task.'
],
'2.1': [
'Our requirement-gathering method combined three visits to Khalsa College, Matunga, with manual distribution of a Google Form among students. The collected responses are real field inputs. The confirmed response total, collection dates and response summary are [To be added]. During development, requirements were translated into role-specific functions, implemented in stages and checked through builds, type checks and isolated tests. Software test counts are reported separately from field-survey evidence.',
'The project used a field-based approach for gathering needs and an iterative approach for software development. All three visits were at Khalsa College, Matunga. We circulated a Google Form manually to obtain student responses, then related the project requirements to the portal’s modules. Collection dates and the validated response count are [To be added]. Technical verification followed implementation and did not substitute for evaluation by actual users.',
'We gathered community information through three visits to the same college and a Google Form shared manually with students. The field responses were genuine; the final exported response sheet and its confirmed totals should accompany the report. Development proceeded through implementation, review and correction of specific defects. This method kept the application’s technical validation separate from claims about the community’s experience.',
'Our work had two connected parts. Fieldwork at Khalsa College, Matunga, provided the setting for manually distributing the Google Form and collecting student inputs. The development work converted placement-support requirements into software features and checked them repeatedly. Dates, attendance and verified survey totals are [To be added]. This separation helps avoid treating application test records as field-survey results.'
],
'2.2': [
'Students were the respondents to the Google Form. The team members were Dhiraj Tendulkar, Vidhi Mahato, Gaurav Mhatre and Varun Patil. The software also models placement coordinators and administrators as operational stakeholders. Names, designations and signed records of any staff consultations are [To be added]. No individual staff statement is presented as an interview quotation without its supporting record.',
'The confirmed interaction involved students receiving the Google Form during the team’s work at Khalsa College. The four members shared the same fieldwork setting and project. Coordinator and administrator needs are represented in the software design. Specific reporting-officer details, mentor-approved interaction notes and signed consultation records are [To be added].',
'Student responses formed the primary field input. Our team worked collectively, so the report does not assign unsupported individual responsibilities or separate datasets to members. Placement staff and administrators are relevant stakeholders because the portal gives them management functions. The identities and recorded comments of consulted staff are [To be added].',
'The stakeholder view starts with the students who received our Google Form. The portal additionally provides staff workspaces for coordination and administration. All four team members contributed to the shared CEP project; individual task-allocation records are [To be added]. Staff names and attributable interview statements will require their original records before inclusion.'
],
'2.3': [
'The domain combines campus placement support, student skill profiles and training coordination. An opportunity describes a role and its requirements; a student profile records interests and skills; an application connects the two. Workshops address preparation needs, while feedback and guidance provide routes for follow-up. Research reporting provides a separate view of student placement experiences.',
'Placement support involves several connected records: student profiles, opportunities, applications, training sessions and requests for assistance. Skill matching helps a student interpret relevance, but formal eligibility and selection still depend on the stated recruitment criteria. The project uses this domain structure to connect information, participation and staff decisions.',
'The portal belongs to the employment-preparation and college-placement domain. It treats a vacancy as more than a title by recording skills, location, eligibility and deadlines. It also recognises that students may need preparation or guidance before applying. This domain model explains why the system includes workshops and support requests alongside opportunities.',
'The project domain is the coordination of career opportunities and preparation within a student community. Profiles describe the applicant, listings describe available roles, and applications record participation. Training, feedback and guidance complete the support cycle. The portal provides an organised workflow within this domain without claiming to make recruitment decisions.'
],
'2.4': [
'The confirmed collection process used a Google Form circulated manually. That process gathers responses but does not itself provide student application histories, workshop capacity control or coordinator decision queues. Skill Bridge adds those operational functions. A detailed map of Khalsa College’s existing placement procedures, including communication channels and responsible staff, is [To be added].',
'For this project, students supplied information through a manually distributed Google Form. A form is suitable for collecting structured answers, but a placement portal must also maintain changing records after collection. Applications, enrolments and guidance requests therefore need additional workflows. Verified details of the college’s pre-existing operational process are [To be added].',
'Our documented starting point is the Google Form collection activity. Survey collection and operational placement management serve different purposes: the first records responses, while the second tracks ongoing actions and decisions. The proposed system addresses the latter through persistent records. A confirmed institutional process diagram is [To be added].',
'The existing process that can be stated with certainty is manual circulation of the Google Form among students. The project extends beyond collection by providing accounts, application tracking and staff responses. It would be inaccurate to attribute undocumented procedures or failures to the college; its approved baseline workflow is [To be added].'
],
'2.5': [
'The related-work discussion compares the collection method used in our project with the operational needs of the portal. Google Forms supported structured student input, while Skill Bridge provides persistent accounts and role-specific follow-up. No named commercial platform or research paper was supplied as an evaluated alternative. Verified literature citations and any formal comparative study are [To be added].',
'Our documented comparison is between a survey collection tool and the proposed placement-support application. The Google Form captures answers at submission; Skill Bridge maintains continuing activities such as application status and workshop participation. A literature review should also include verified published work where available. Research-paper and book references are [To be added].',
'The project did not establish a benchmark against a named external placement product. The available comparison concerns function: a form collects responses, whereas the portal connects those information needs with accounts, workflows and records. Published studies and independently assessed alternatives must be cited only after verification; those references are [To be added].',
'Google Forms was part of our requirement collection, but the developed website has a broader operational purpose. It provides continuing access to profiles, listings, decisions and support requests. No comparative performance claim against another product is made here. Details of any research papers, books or formal product evaluations are [To be added].'
],
'2.6': [
'The selected stack is visible in the project implementation. React and TypeScript support the interface and shared data contracts; Express handles API requests; SQLite stores persistent records. Vite builds the frontend, Tailwind CSS supports styling and Recharts renders research charts. These are implementation choices, not evidence that other technologies were experimentally benchmarked.',
'The technical study concentrated on the tools used to build the application. React organises screens into components, TypeScript checks data contracts, and Express provides the server endpoints. SQLite supplies relational storage without a separate database service. Vite, Tailwind CSS and Recharts complete the build, presentation and charting requirements.',
'Our application uses a TypeScript-based frontend and server with SQLite persistence. The technology selection suits a college project that needs interactive screens, authenticated requests and related records. The table below identifies each tool’s actual role. It does not imply a comparative experiment with frameworks that are absent from the repository.',
'The implementation combines React components with an Express API and a SQLite database. TypeScript checks the contracts between data and code, while Vite prepares the frontend build. Tailwind CSS and Recharts address interface styling and research visualisation. The stack is described according to its use in Skill Bridge rather than through generic technology claims.'
],
'2.7': [
'The practical gap is the connection between gathered information and a usable support workflow. Collecting student needs does not automatically provide relevant listings, application histories or staff follow-up. Skill Bridge addresses that gap through separate workspaces backed by a common database. A claim of academic novelty is outside the evidence available for this project.',
'The proposed solution is needed because response collection and ongoing service delivery are separate tasks. The portal brings opportunity discovery, applications, workshops and guidance into a consistent workflow. Its contribution is this integrated implementation for the project context, rather than a new machine-learning method or an experimentally proven research breakthrough.',
'The gap identified for system design is continuity: information about a student’s needs should connect to opportunities and recorded actions. Skill Bridge creates that continuity through profiles, matching explanations, applications and support queues. The project makes a practical contribution through integration; formal novelty against published research remains [To be added].',
'Our solution addresses the transition from understanding student needs to supporting concrete next steps. The portal links profiles and listings with applications, training and guidance. This is the project’s implementation gap, not a claim that no comparable systems exist. Any broader research comparison requires verified literature.'
],
'2.8': [
'The main technical challenges were preserving records during restoration, enforcing student–coordinator access boundaries and keeping validation consistent. Startup configuration and optional database values also required attention. The fieldwork challenges that can be quantified, such as incomplete submissions or participation levels, are [To be added]. These categories are kept separate so implementation defects are not misreported as community findings.',
'Development required careful handling of permission boundaries, malformed content and database initialisation. Another challenge was ensuring that a successful interface message reflected an actual server save. Collection-related difficulties and their frequency are [To be added] from the field records. The final solution was reviewed against these technical concerns through isolated tests.',
'The project’s technical difficulties centred on data integrity and predictable behaviour. Restoring records must preserve relationships, users must receive only permitted data, and production startup must not depend on demo accounts. Documented field difficulties, if any, should be recorded from the visit notes. They are not inferred from problems encountered while programming.',
'Reliable coordination required more than adding pages. We had to account for access control, invalid inputs, duplicate actions and safe database startup. A further requirement was to protect individual survey responses while keeping public summaries usable. Specific issues experienced during survey collection are [To be added] from the original records.'
],
'3.1': [
'Skill Bridge provides connected workspaces for students, placement coordinators and administrators. Students discover opportunities and request support; coordinators review and respond; administrators maintain protected configuration and recovery tools. This structure turns the project requirements into a sequence of recorded actions, with the server controlling permissions.',
'The solution is a web portal that gives each role the tools needed for its work. Students manage their own placement activities, coordinators operate shared queues, and administrators handle system maintenance. A common API and database connect these views so that a recorded decision can be retrieved in the appropriate workspace.',
'The proposed solution uses one application with distinct access levels. A student’s account supports personal actions, while staff accounts support coordination and administration. Shared records connect the interfaces without giving every user the same permissions. This design is central to both the project demonstration and its intended operational use.',
'The portal organises placement support around the people using it. Student actions create records, coordinator actions update their progress, and administrative tools protect the system’s configuration and data. The solution therefore combines an understandable interface with server-enforced control over what each account can do.'
],
'3.2': [
'The browser runs the React interface and sends requests through the API service. Express receives these requests, resolves the session and checks the required role. Valid operations read or update SQLite, after which the result is returned to the interface. In production mode, Express also serves the built frontend assets. Environment configuration is loaded before database initialisation.',
'The architecture has three main layers: the React user interface, the Express application server and SQLite storage. The interface does not grant authority by itself. Each protected request is checked on the server before database access. Configuration controls the port, database location and allowed origins; the production server can also deliver the compiled frontend.',
'A client–server architecture separates presentation from data operations. React renders the screens, an API service sends requests, and Express performs validation and permission checks. SQLite stores the resulting records. Production serving combines the compiled frontend and API behind the server, while configuration is established before storage is opened.',
'The frontend communicates with the server through HTTP API calls. Session and role checks determine whether a request can proceed, then the server performs the necessary database operation. The interface updates from the returned result. This arrangement centralises authority and persistence instead of relying on browser-only state for important records.'
],
'3.3': [
'The principal flow begins with authentication and role identification. A student reviews relevant opportunities, checks the explanation and eligibility text, then saves or applies. The coordinator receives the application, records a decision and makes that status available to the student. Workshops and guidance follow similar request-and-response sequences.',
'The process moves from sign-in to a role-specific workspace. Students explore options and submit actions; the server validates them and records them. Staff then review the relevant queue and respond. The updated state is retrieved by the student. Failed or unauthorized requests should produce a clear error rather than a success message.',
'The workflow connects discovery with follow-up. After authentication, a student chooses an opportunity or support service. The server checks the request and stores it. A coordinator can then review the record and update its status. Returning to the student workspace shows the latest persisted result.',
'A typical transaction begins when a signed-in user selects an action. The API checks the session, role and input before changing data. The result then returns to the interface. For applications, this sequence continues with coordinator review and a student-visible decision, forming a traceable cycle.'
],
'3.4': [
'The modules share data where necessary but retain clear responsibilities. Authentication identifies the user, operational modules manage actions, and reporting summarises the relevant records. Administrative functions remain separate from ordinary student and coordinator work.',
'Each module represents a recognisable task rather than an isolated page. Profiles support matching, opportunities support applications, and workshops support preparation. Feedback and guidance provide follow-up, while reporting and administration serve different access needs.',
'Module boundaries follow the project’s user activities. Common session and API services support the screens, but application decisions, workshop enrolments and research records remain distinct entities. This makes each workflow easier to understand and test.',
'The solution is divided into modules with specific responsibilities. Shared services handle communication and state, while the functional modules manage their own records. The table below connects each module with the activity it supports.'
],
'3.5': [
'The main advantage is continuity between student actions and coordinator responses. Explained matching adds context to opportunity discovery, and persistent records allow users to return to their work. Role-specific access reduces ambiguity during use. These are supported capabilities of the design; measured improvements in placement success or staff workload have not been established.',
'The portal offers a consistent place to find opportunities, act on them and follow the response. Students receive matching reasons instead of an unexplained score, and staff use dedicated management views. Database-backed records support continuity across sessions. Long-term benefits require observation after actual deployment.',
'The proposed system improves organisation by connecting related tasks through shared records. Its access model helps separate personal student work from institutional operations. Matching explanations and visible statuses improve the information available for decisions, though the project does not quantify an increase in employment outcomes.',
'Skill Bridge’s advantages come from its connected workflow, understandable matching and differentiated permissions. The interface can show a student’s own progress while allowing coordinators to manage the broader queue. These features provide a basis for better coordination; their institutional impact must be measured through subsequent use.'
],
'4.1': [
'The design uses typed records for profiles, opportunities, applications, workshops and research responses. Relationships are stored in SQLite rather than reconstructed only in the interface. Validation checks input before persistence, while foreign keys and uniqueness constraints protect important relationships. The browser state presents these records but does not replace the database as the authoritative store.',
'System design begins with the records needed by each workflow. Users own personal actions, opportunities receive applications, and workshops receive enrolments. TypeScript describes the expected structures, and SQLite enforces relational rules. Server-side validation provides another boundary before data is stored.',
'The design separates display state from persistent state. Components render information, shared context coordinates refreshes, and the API performs protected operations. Database relationships link students to applications and workshops. This structure supports account isolation and reliable retrieval after a page refresh.',
'The internal design combines typed application models with relational storage. It avoids treating a visible button as an authorization mechanism: the server independently checks each protected request. Validation, uniqueness constraints and transactions are used where invalid or repeated actions could create inconsistent records.'
],
'4.2': [
'The use cases are organised around four actors: public visitor, student, placement coordinator and administrator. Public access is limited to appropriate information and aggregate research. A student works with personal records; staff operate management functions. The server checks these boundaries even when an endpoint is called directly.',
'Actor-based design makes access expectations explicit. Visitors can explore permitted public information, students use personal placement tools, coordinators manage operational records, and administrators maintain protected settings. This distinction is reflected in both navigation and API authorization.',
'The use-case model identifies what each role is allowed to accomplish. Student actions concern the signed-in account, coordinator actions concern placement operations, and administrator actions concern system maintenance. Public research views use aggregates rather than individual respondent records.',
'The principal actors have different responsibilities. A visitor sees public information; a student applies or requests support; a coordinator reviews operational work; an administrator maintains the system. The permissions table defines these boundaries independently of the presentation layer.'
],
'4.3': [
'The application workflow requires a valid student session, a selected opportunity and an accepted request. Duplicate applications are rejected. Coordinator review changes the stored application status, which is later displayed to the student. For workshop enrolment, the server also checks capacity and existing participation before committing the record.',
'The detailed workflow includes validation and failure paths. A repeated application or enrolment should not create another record. Workshop capacity must be checked during the operation, and a rejected request must leave the prior state intact. Successful staff updates become visible through subsequent data retrieval.',
'Workflow design accounts for both successful and unsuccessful requests. The server verifies ownership, permission and input before writing. A duplicate or invalid request returns an error, while a successful write returns confirmation. Enrolment uses transactional handling to keep participation and capacity consistent.',
'The workflow model places checks before persistence. Authentication establishes identity; authorization establishes permission; validation checks the requested change. Application review and workshop participation then operate on stored records. The interface displays the server result rather than assuming every submitted action succeeded.'
],
'4.4': [
'The module design connects frontend pages to shared context and API methods. Server endpoints operate on the corresponding database entities. The matching function is a deterministic weighted process: it compares profile information with listing fields and returns a score together with reasons. It is advisory and does not predict hiring probability.',
'Internally, the pages use a common context and API service to retrieve and update data. Express endpoints apply the relevant checks and database operations. Opportunity matching uses fixed rules with visible reasons, allowing students to understand why a listing is considered relevant. The score should not be interpreted as a likelihood of employment.',
'Module implementation is supported by typed models and shared services. Data changes pass through the API rather than remaining only in browser state. The matching module compares department, preferred role, skills, location and a detected percentage cutoff. Its output is an explanation of fit, not a trained predictive model.',
'The database model and matching process are important parts of the module design. Relational tables retain user actions, while a rule-based function produces an understandable opportunity score. The function helps exploration but leaves detailed eligibility and selection decisions to the stated recruitment conditions.'
],
'5.1': [
'Development followed an iterative cycle of implementation, review and correction. The team maintained the existing application while addressing verified issues in permissions, restoration, validation and startup. Type checks, production builds and isolated tests were used after changes. This process allowed defects to be examined without resetting the real project database.',
'The application was developed through repeated implementation and validation. Features were reviewed in relation to the intended student and coordinator workflows, then specific faults were corrected. The final checks included compilation, isolated API workflows and production-mode serving. Existing project data was kept separate from test data.',
'Our development method relied on small, verifiable changes to the existing project. Reviews identified defects, the relevant code was adjusted, and checks were rerun. The work covered both visible functionality and less visible concerns such as database integrity and startup configuration. Disposable databases supported repeatable testing.',
'Implementation progressed through a sequence of feature work, inspection and regression checks. The aim was to preserve working behaviour while correcting specific problems. Production compilation and isolated tests provided evidence after changes, and the real database was protected from test resets.'
],
'5.2': [
'The source is organised into React pages, reusable components, shared context, API services and server modules. AppContext coordinates session and data refreshes. The API service sends authenticated requests, and Express performs role checks and validation. SQLite retains the resulting records. This structure implements the proposed separation between student actions, coordinator decisions and administrative maintenance.',
'Each functional area is implemented through a page, shared service calls and server endpoints. Authentication establishes the current account; context exposes the relevant state to components. The server determines whether an operation is permitted and writes accepted changes to SQLite. This connects the proposed solution directly to the source organisation.',
'The frontend modules use shared context and API methods instead of managing unrelated local copies of important records. The backend validates requests and applies the corresponding database operation. Coordinator updates and student actions therefore refer to the same stored entities. Administrative backup and diagnostic functions are kept behind elevated permissions.',
'The implementation links user-facing screens to protected operations. React renders the workspace, the API service handles requests, and Express checks identity, role and input. The database stores accepted updates for later retrieval. The same pattern is used across applications, workshops, feedback and guidance, with workflow-specific checks.'
],
'5.3': [
'The interface gives students and coordinators different navigation and actions. Students see personal application and support tools, while coordinators receive management views. Forms and status messages help users understand what happened after an action. Responsive styling is implemented, but a complete interactive mobile and accessibility walkthrough remains a separate verification item.',
'The user interface is organised around the task and role. Personal student records are presented separately from coordinator queues and administrative controls. Feedback messages reflect API outcomes, and input checks help prevent invalid submissions. Layout styling supports different screen sizes; final device-based usability observations are [To be added].',
'Interface design emphasises distinct workspaces and visible state. Students can follow their own records without using staff management screens. Coordinators can review and update operational work through dedicated controls. Responsive styles are present, although this report does not claim a completed evaluation on every device or assistive technology.',
'The frontend translates the access model into clear navigation. Student actions, coordinator decisions and administrator controls appear in their respective workspaces. Loading and error handling support the interaction around API requests. A recorded browser walkthrough across desktop and mobile devices is [To be added].'
],
'5.4': [
'The following locations are reserved for screenshots of the developed application. Each image should show the actual current interface and use test accounts with no private student information visible.',
'Screenshots should document the implemented screens rather than a proposed mock-up. The reserved figures below identify the required views; use the current application and redact personal details before insertion.',
'Visual evidence of the application belongs in the figure spaces below. Capture the working version with appropriate test records so that the images demonstrate the implementation without disclosing student data.',
'The screenshot section is reserved for evidence from the actual portal. Insert the listed views after checking that they match the submitted version and do not expose confidential account or survey information.'
],
'6.1': [
'Validation covered normal actions, invalid input and unauthorized requests. The workflow suite used a disposable SQLite database, allowing records to be created and removed without changing the real database. The representative cases below show how the tests relate to the project requirements.',
'The test approach included positive and negative cases. It checked whether permitted actions succeeded and whether duplicate, malformed or unauthorized requests were rejected. Isolated databases made these checks repeatable. The table summarises the principal scenarios rather than listing every assertion.',
'Tests were selected around the behaviour needed by users and the rules protecting their records. This included account isolation, application decisions, capacity checks and safe restoration. A separate production check examined startup and serving. The cases below connect these checks with expected outcomes.',
'The project was checked through acceptance, workflow, lifecycle and serving suites. Together they cover calculations, protected operations, database initialisation and the production server. These automated checks use controlled data; they are distinct from acceptance by students or college staff.'
],
'6.2': [
'The latest recorded verification passed the TypeScript check, production build and all four automated suites. The suite totals are shown below. Lint completed with warnings. These results establish the behaviour covered by the tests; they do not prove that every browser interaction or deployment environment has been validated.',
'The available technical evidence shows a successful build and type check, followed by passing results in all four suites. The total is 157 reported checks. Lint warnings remain for review. The result is encouraging for the tested scope, while live hosting and complete visual interaction checks require their own evidence.',
'The final recorded test run reported no failures across the listed suites. Production serving included static assets, direct routes and a provisioned administrator’s session. Compilation also passed. The results should be read as evidence for tested cases, not a universal guarantee of correctness or security.',
'The recorded verification completed successfully across acceptance, workflow/security, production lifecycle and serving checks. TypeScript and the production build also passed. Lint completed with warnings. No numerical claim about real-user satisfaction or employment outcomes follows from these software checks.'
],
'6.3': [
'User acceptance testing should establish whether students and staff can complete the intended tasks without assistance. A signed UAT record, participant details and observed outcomes are [To be added]. The automated acceptance suite checks software behaviour and must not be treated as evidence that the college formally accepted the system.',
'A practical UAT session should cover finding a role, submitting an application, enrolling in training and reviewing a request from the coordinator side. Verified participant observations and approval are [To be added]. Passing automated checks does not replace this direct assessment of usability.',
'Acceptance by actual users requires a record of attempted tasks, difficulties and feedback. Those results and signatures are [To be added]. The project’s automated acceptance checks are technical tests; they do not establish institutional approval or successful task completion by field participants.',
'The remaining UAT evidence should identify the users, tasks, results and approval status. These details are [To be added]. Students and staff should verify the workflows in the browser, including error messages and recovery, before a formal acceptance claim is made.'
],
'6.4': [
'The real Google Form responses belong to the fieldwork record. Exact findings, approved quotations and the final response summary are [To be added]. The reporting-officer feedback form is included as a blank annexure. No statement has been attributed to a participant or staff member without a supplied record.',
'Stakeholder feedback should be presented from the actual responses and signed forms. The verified summary and any permission to quote participants are [To be added]. Annexure D provides an unfilled reporting-officer form so that feedback can be recorded without inventing an endorsement.',
'The report recognises the Google Form collection as genuine fieldwork. The response export, analysed findings and documented staff comments are [To be added]. Feedback is not reconstructed from sample text inside the application or from the software test results.',
'The final feedback section should contain the findings drawn from the collected responses and any signed staff assessment. Those details are [To be added]. The blank form in Annexure D provides space for that assessment while leaving the authority to approve the work with the reporting officer.'
],
'6.5': [
'Evaluation currently supports functional reliability within the tested scope. No controlled measurements of response time, throughput, concurrent-user capacity or resource consumption were supplied. These performance values are [To be added]. Local production serving demonstrates successful operation, but a load test on the target host is needed before making scalability claims.',
'The available results concern correctness and startup rather than measured speed. A production build and passing serving checks show that the application can run locally in production mode. Response-time and load measurements are [To be added]. They should be collected under a documented workload and hosting configuration.',
'Performance evaluation must distinguish a functioning system from a benchmarked one. The tests verify expected responses and protected operations, but they do not report latency distributions or sustained concurrency. A repeatable workload, hardware description and measured results are [To be added].',
'The present evidence supports functional validation. It does not provide an accuracy percentage for matching or a measured server-capacity figure. Timing, memory and load-test results are [To be added]. Any later performance claim should identify the environment, workload and measurement method.'
],
'7.1': [
'The developed outputs include the portal source, SQLite-backed workflows, automated tests, configuration examples and project documentation. These are available project artefacts. The date and acknowledgement of formal submission or handover to Khalsa College are [To be added]. Photographs and signed records remain separate supporting attachments.',
'The project produces a working web portal, its database implementation, test scripts and supporting instructions. This report and the annexures document those outputs. A signed receipt or approved handover record is [To be added], so availability of the artefacts is not presented as proof of institutional deployment.',
'The deliverables comprise the application, source modules, database schema, verification scripts and documentation. The repository address and formal submission details are [To be added]. The table below identifies what each artefact contributes without assuming that a live handover has already been approved.',
'The completed technical outputs are the portal implementation, persistent data model, checks and operating instructions. Supporting documentation includes this report and its annexures. Organisation-level handover, repository publication and hosting details are [To be added] where they have not been supplied.'
],
'7.2': [
'The achieved technical result is a connected portal with protected student and staff workflows. The previous startup and schedule-validation failures were corrected, and the latest four-suite run passed. Production-mode checks verified serving, administrator authentication and an authorized update. These results describe software operation rather than a change in student placement outcomes.',
'The application now connects the main placement-support functions through persistent records and differentiated access. The final recorded checks passed after the identified defects were corrected. Fresh production operation was also tested locally. Verified analysis of the real field responses remains [To be added] and is not inferred from test data.',
'The project achieved the implementation of the planned role-based workflows and a passing automated verification run. Matching returns reasons, staff decisions update records, and restoration preserves tested relationships. The result is a technically demonstrated portal; community-level outcome measures require additional evidence.',
'The main outcome is an implemented system that supports the intended student–coordinator cycle. Local production checks and the full test command passed in the latest review. This supports readiness for further browser and host validation. It does not establish a measured increase in placements or institutional adoption.'
],
'7.3': [
'The portal offers the college a possible way to organise placement-support activities and preserve their history. Students can obtain clearer next steps, while coordinators can work from structured queues. Actual adoption, workload reduction and student benefit must be confirmed through use and feedback. A measured organisational impact summary is [To be added].',
'The expected organisational benefit is better continuity between a student request and a staff response. Shared records can support follow-up and make responsibilities clearer. These benefits remain subject to adoption and evaluation at the college. No quantified reduction in effort or improvement in placement rates is claimed.',
'The system provides a basis for more organised placement support through records that connect users and actions. Its impact depends on maintained listings, staff participation and student use. Evidence of deployment, sustained adoption and measured benefit is [To be added]. The report therefore distinguishes technical delivery from organisational effect.',
'Skill Bridge can assist the college by keeping opportunities, participation and support requests in an organised workflow. Whether this improves everyday practice must be assessed after use. Adoption records and before-and-after measures are [To be added]; the available technical results alone cannot establish that impact.'
],
'7.4': [
'The delivered features support the educational and employment-preparation aims of SDG 4 and SDG 8. Workshops and guidance address preparation, while opportunity discovery and application records support access to career information. The contribution is a practical digital support mechanism; verified long-term SDG outcomes are beyond the current evidence.',
'The project’s SDG contribution lies in the services it makes available: learning support, career guidance and organised access to opportunities. These functions relate to SDG 4 and SDG 8. A stronger impact assessment would follow students over time and document actual use rather than rely on the presence of features alone.',
'The implementation reflects the selected SDGs through training access and employment preparation. Its role is to support students and coordination, not to guarantee employment. Continued monitoring would be needed to connect use of the portal with measurable educational or work-related outcomes.',
'The SDG connection is visible in the project’s purpose and functions. Skill-development opportunities support SDG 4, while career information and application support relate to SDG 8. The report records this contribution at the implementation level and leaves measured long-term impact for subsequent evaluation.'
],
'8.1': [
'Skill Bridge connects the community project with a practical placement-support application. The three visits to Khalsa College, Matunga, and manual Google Form collection provide the fieldwork setting. The technical work establishes differentiated access, persistent workflows and a passing automated test baseline. Final photographs, signed records and user-acceptance evidence will complete the submission record.',
'The project brought together fieldwork at Khalsa College and the development of a role-based portal. Students supplied genuine responses through the circulated Google Form, while the software work produced connected placement and support functions. The recorded checks show technical progress. The remaining documentary evidence concerns field totals, photographs, approvals and direct user evaluation.',
'The completed implementation demonstrates how student activities and coordinator decisions can share a consistent workflow. All three field visits were undertaken at Khalsa College, Matunga, and the survey was collected manually through Google Forms. Technical verification is documented separately from community outcomes. The final report should be accompanied by the original evidence and signed records.',
'Skill Bridge provides a concrete outcome for the CEP work: a portal with distinct access, persistent records and verified local production behaviour. The project is grounded in three visits and real student data collection at Khalsa College. Its continuing value will depend on careful deployment, maintained information and documented feedback from users.'
],
'8.2': [
'The implementation shows that permission checks, validation and database relationships are central to a reliable portal. A successful build alone is insufficient; startup and workflow tests exposed problems that required correction. Matching explanations are also important because a numerical score needs context. Field-response findings must be drawn from the original response export.',
'A key finding from development is that the visible interface depends on less visible safeguards. Role authorization, transactional restoration and safe initialisation protect the work performed through the screens. Another finding is the need to distinguish automated acceptance from stakeholder approval. Neither should be used as a substitute for the other.',
'The work highlights the importance of connecting records without mixing permissions. It also shows why fresh-database testing is necessary alongside compilation. The matching process is useful as an explanation of relevance, but it remains limited by profile quality and the stated rules. Findings from the actual survey are [To be added].',
'The strongest technical lesson is the need to verify complete workflows rather than individual pages alone. Data integrity, account isolation and startup configuration affect every user journey. The project also requires a clear distinction between real survey evidence and controlled software tests when presenting results.'
],
'8.3': [
'Before institutional use, assign an operational owner, verify the deployment configuration and complete a student–coordinator browser walkthrough. Keep backups and test recovery periodically. Add the original Google Form summary, visit dates and signed attachments to the report. Review privacy requirements before publishing any research output.',
'The next practical steps are controlled deployment, user acceptance and completion of the evidence record. Staff should agree who maintains listings, responds to requests and manages backups. Public reports should remain aggregate, with individual responses restricted. Field photographs and signed forms should be attached before submission.',
'I recommend a small supervised rollout before wider use. Confirm role access, data persistence and recovery on the actual host, then record student and coordinator feedback. Maintain a clear owner for each operational task. Complete the documentary gaps using original field records rather than estimates.',
'Operational preparation should include a responsible administrator, a maintained backup schedule and a tested recovery process. The team should complete browser verification and obtain formal feedback. Survey totals, dates and signatures should be filled from verified records, and confidential response data should remain protected.'
],
'8.4': [
'Possible future work includes configurable matching rules, opt-in reminders and richer follow-up reporting. These would require additional implementation and evaluation. Accessibility testing and measured performance on the deployment host would also improve confidence. None of these proposed extensions is presented as an existing feature.',
'Future development could add carefully controlled notifications, more configurable matching and reporting across longer periods. Any extension should preserve privacy and be evaluated with users. A documented accessibility review and host-level performance study would complement the existing technical tests.',
'Further versions may support reminders, configurable matching weights and broader progress reporting. These are potential enhancements rather than completed deliverables. Their value should be assessed through user feedback, and the underlying permission and recovery mechanisms should remain part of regression testing.',
'The project can be extended through user-approved notifications, adaptable matching criteria and longer-term reporting. These additions should follow evidence of need. Future work should also measure accessibility and performance under realistic use, while retaining the existing boundaries around personal and survey data.'
]
}

ABSTRACTS = [
'''Skill Bridge is a community employment and skill matching portal developed as part of our Community Engagement Project at Khalsa College, Matunga. Our team completed three visits to the college and gathered real student inputs by manually circulating a Google Form. The project addresses the need to connect opportunity information, student interests, skill preparation and placement follow-up in a clear workflow. Its objective is to provide useful student services while giving coordinators a separate workspace for operational decisions.

The application provides profiles, opportunity browsing, explained matching, saved opportunities, applications, workshop enrolment, feedback and guidance requests. Coordinator functions include managing listings, reviewing applications, maintaining training records and responding to requests. Administrative functions cover protected content, diagnostic queries and backup restoration. Public research views use aggregate information, while access to individual survey responses is restricted.

The implementation uses React, TypeScript, Vite, Tailwind CSS and Recharts for the frontend, with an Express server and SQLite persistence. Matching is a deterministic weighted process based on profile and opportunity fields. It returns reasons for its assessment and does not predict the probability of employment. Server-side authorization, input validation and database constraints support reliable operation.

The latest recorded verification passed 157 automated checks across acceptance, workflow, lifecycle and production-serving suites. The TypeScript check and production build also passed. These results establish the tested technical behaviour, including fresh production startup and administrator operations. They do not establish a measured improvement in placement outcomes. The portal provides a practical basis for organised placement support; verified survey totals, signed user acceptance and measured institutional impact remain to be added to the final evidence record.''',
'''This Community Engagement Project presents Skill Bridge, a web portal intended to make placement support easier to follow for students and coordinators. The fieldwork was carried out through three visits to Khalsa College, Matunga. We collected genuine responses by manually sharing a Google Form among students. The work focuses on the connection between understanding student needs and providing a system through which opportunities, applications, training and guidance can be managed.

Students use a personal workspace to maintain profile information, explore openings, read matching explanations, apply for opportunities and enrol in workshops. They can also submit feedback and request guidance. Coordinators receive separate management views for reviewing applications and handling operational work. Administrators maintain protected configuration and recovery functions. The access model is enforced through server checks rather than interface visibility alone.

The portal uses React and TypeScript, supported by Vite, Tailwind CSS and Recharts. Express provides the API, and SQLite stores related records. A rule-based scoring process compares department, role preference, skills, location and a detected academic cutoff. The output is advisory: it explains relevance without claiming to determine employer selection.

Technical validation included compilation, isolated workflows, database lifecycle checks and production serving. The latest recorded run passed 157 automated checks, along with TypeScript and the production build. Lint completed with warnings. The results show that the tested functions operate as expected, but direct user acceptance and live-host verification remain separate activities. Skill Bridge offers a structured support mechanism aligned with learning and employment preparation. Confirmed field-response statistics, signed feedback and evidence of organisational adoption are to be added from the original records.''',
'''Skill Bridge was developed to connect student placement activities with coordinator follow-up through a shared web application. The project formed part of our CEP work at Khalsa College, Matunga, where all three team visits took place. Student information was gathered manually through a circulated Google Form. The purpose was to support a more connected process for opportunity discovery, preparation, applications and requests for assistance, while keeping responsibilities and access distinct.

The solution contains student profiles, opportunity listings, saved records, applications, workshop participation, feedback and guidance. Coordinators manage the operational queues and record decisions. Administrators handle protected system documents, approved diagnostics and backup restoration. Research information is presented publicly through summaries, with individual respondent records limited to authorized staff. Persistent records allow actions and decisions to be retrieved across sessions.

The technical structure consists of a React and TypeScript frontend, an Express API and a SQLite database. Vite prepares the frontend build, Tailwind CSS provides styling and Recharts supports charts. Matching uses fixed weighted comparisons rather than machine learning. It provides reasons and eligibility cautions so that students can interpret the result instead of treating it as a hiring prediction.

The final recorded verification passed 37 acceptance checks, 97 workflow and security checks, 14 lifecycle checks and 9 production-serving checks. The build and TypeScript checks also passed. This evidence supports the tested local operation of the portal, including production startup and administration. It does not replace field-based user acceptance or demonstrate improved placement rates. The project delivers a practical system and a documented technical baseline. Verified survey analysis, visit evidence and formal acceptance records remain necessary supporting material for the final submission.''',
'''Our Community Engagement Project resulted in Skill Bridge, a portal for student employment preparation and placement coordination. The team visited Khalsa College, Matunga, three times and gathered real student responses by manually distributing a Google Form. The project’s central concern is continuity: students should be able to move from finding an opportunity to taking action and receiving a response, while staff should have an organised view of the work requiring attention.

The application separates student, placement coordinator and administrator access. Its functions include profile management, opportunity discovery, explained matching, application tracking, workshops, feedback, guidance and research summaries. Coordinator actions update shared operational records, while administrative tools support configuration and data recovery. Individual survey responses are restricted, and public reporting uses aggregate information.

React, TypeScript, Vite, Tailwind CSS and Recharts form the frontend stack. The backend uses Express and SQLite. Matching is implemented as a deterministic scoring function that compares selected profile and listing attributes. Because it is a relevance aid rather than a predictive model, the interface also provides reasons and eligibility information. Authentication, server-side permissions, validation and relational constraints support the main workflows.

The latest recorded test run passed 157 checks across four suites, and both the production build and TypeScript verification succeeded. Fresh production serving, administrator login, an authorized update and logout were included in the checks. These results describe technical behaviour under the test conditions. They do not demonstrate live institutional adoption, performance under load or a change in employment outcomes. The project offers a usable foundation for coordinated placement support. Original survey totals, photographs, signed feedback and user-acceptance results are to be attached as the remaining fieldwork evidence.'''
]
